# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: feae2d2454bbea4a63c3cf6ac24db4591f2be08dfce4c296404cafd3eaee850601136fa87ff08f68b0ea9ea36bbd6a0516e74f64f7ff047f547222e2bfd5161c

test:
  secret_key_base: 5e156a344a02b3b24bb5bfa51bcd477534dcab63675a22de1f2e31b260aa6a484c4fca7e19ef2c8f3292b404e45e888b8a4a3f3ad3d8b9d8b625c3dfe47cdf65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
